### ISSUE TITLE
Include bootstrap manually - scripts from /dist not loaded

### ISSUE THREAD

**Issue by GMTeams** [netzmacht/contao-form-validation#3]
In your manual you wrote:
_Set the assets path to the http://formvalidation.io/ library in System settings -> form validation_

Actually my form is not validating. There are some things I don't understand:

- The directory /dist which comes from formvalidation.io doesn't have included the bootstrap framework (bootstrap.min.css & bootstrap.min.js). That means I have to include this files manually?

- I have entered the path for /dist directory in contao settings, I can find the CSS Code from formValidation.css in the collection.css but I can't find the code from formValidation.js neither in the collection.js nor elsewhere in the source code.

- I already had installed contao-bootstrap/form, so this should provide a bootstrap HTML-Layout for the form. But this is not in the dependencies of contao-form-validation listed - do I need this?

Maybe you can help me, thank you very much!

**Comment by dmolineus** [comment]
It's quite a long time ago I wrote this extension. Maybe the structure of formvalidation has changed. So here's whats required:

> The directory /dist which comes from formvalidation.io doesn't have included the bootstrap framework (bootstrap.min.css & bootstrap.min.js). That means I have to include this files manually?

If you want to work with bootstrap, you have to include it for your own. This lib only handles the formvalidation integration which can be used without bootstrap as well.

> I have entered the path for /dist directory in contao settings, I can find the CSS Code from formValidation.css in the collection.css but I can't find the code from formValidation.js neither in the collection.js nor elsewhere in the source code.

This extension expects following paths inside the defined directory:

 - `js/formValidation.min.js`
 - `css/formValidation.min.css`

Maybe this paths has changed in the meanwhile in the provided dist directory.

> I already had installed contao-bootstrap/form, so this should provide a bootstrap HTML-Layout for the form. But this is not in the dependencies of contao-form-validation listed - do I need this?

You **can** use contao-bootstrap/form to provide a bootstrap form html markup. But you don't have to. You may also work with custom form templates or use one of the other supported frameworks.

**Comment by GMTeams** [comment]
> If you want to work with bootstrap, you have to include it for your own. This lib only handles the formvalidation integration which can be used without bootstrap as well.

Ok, now things get clearer for me.

> This extension expects following paths inside the defined directory:
js/formValidation.min.js
css/formValidation.min.css

The paths are the same. It also was a mistake that the CSS appears in the collection.css. None of both is appearing in FE. Maybe there is another extension making changes, e.g. I also have contao-theme-plus installed. But it's not a big problem, I can also include the files in the page layout.

> You can use contao-bootstrap/form to provide a bootstrap form html markup. But you don't have to. You may also work with custom form templates or use one of the other supported frameworks.

Ok, thanks!
